/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出可用模型
         * @description 返回 OpenAI 兼容模型清单。
         */
        get: operations["listOpenAIModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取模型详情 */
        get: operations["getOpenAIModel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建聊天补全 */
        post: operations["createChatCompletion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建文本补全 */
        post: operations["createLegacyCompletion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建多模态响应 */
        post: operations["createResponses"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/images/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 生成图像 */
        post: operations["generateImages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/{model}:generateContent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 生成 Gemini 响应 */
        post: operations["generateGeminiContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/{model}:streamGenerateContent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gemini 流式生成 */
        post: operations["streamGeminiContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/{model}:countTokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 计算 Token */
        post: operations["countGeminiTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1beta/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出 v1beta 模型 */
        get: operations["listGeminiBetaModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1beta/models/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 v1beta 模型详情 */
        get: operations["getGeminiBetaModel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/api/management/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上传凭证 */
        post: operations["uploadCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/api/management/credentials/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 校验单个凭证 */
        post: operations["validateCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/api/management/credentials/validate-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 批量校验凭证 */
        post: operations["validateCredentialBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/api/management/models/variant-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取模型变体配置 */
        get: operations["getVariantConfig"];
        /** 更新模型变体配置 */
        put: operations["updateVariantConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/api/management/models/generate-variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 生成模型变体列表 */
        get: operations["generateVariants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/api/management/models/parse-features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 解析模型特性 */
        post: operations["parseModelFeatures"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/api/management/assembly/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 装配台总览 */
        get: operations["getAssemblyDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/api/management/assembly/routing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前路由状态 */
        get: operations["getRoutingState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/api/management/assembly/dry-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 内联装配计划差异预览 */
        post: operations["dryRunAssemblyPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/api/management/assembly/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出演练计划 */
        get: operations["listAssemblyPlans"];
        put?: never;
        /** 保存当前路由为计划 */
        post: operations["createAssemblyPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/api/management/assembly/plans/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取计划详情 */
        get: operations["getAssemblyPlan"];
        put?: never;
        post?: never;
        /** 删除计划 */
        delete: operations["deleteAssemblyPlan"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/api/management/assembly/plans/{name}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 应用计划 */
        put: operations["applyAssemblyPlan"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/api/management/assembly/plans/{name}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 回滚计划 */
        put: operations["rollbackAssemblyPlan"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/api/management/assembly/plans/{name}/dry-run/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 计划应用差异预览 */
        get: operations["diffApplyAssemblyPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/api/management/assembly/plans/{name}/dry-run/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 计划回滚差异预览 */
        get: operations["diffRollbackAssemblyPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/api/management/routing/persist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 手动持久化路由状态 */
        post: operations["persistRoutingState"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/api/management/routing/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 恢复路由状态 */
        post: operations["restoreRoutingState"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/api/management/assembly/cooldowns/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 清理路由冷却状态 */
        post: operations["clearRoutingCooldowns"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OpenAIModelsResponse: {
            data?: components["schemas"]["OpenAIModel"][];
            object?: string;
        };
        OpenAIModelResponse: {
            data?: components["schemas"]["OpenAIModel"];
        };
        OpenAIModel: {
            id?: string;
            object?: string;
            /** Format: int64 */
            created?: number;
            owned_by?: string;
            capabilities?: {
                [key: string]: unknown;
            };
        };
        ChatCompletionsRequest: {
            model: string;
            messages: components["schemas"]["ChatMessage"][];
            temperature?: number;
            top_p?: number;
            max_tokens?: number;
            stream?: boolean;
            response_format?: {
                [key: string]: unknown;
            };
        };
        ChatMessage: {
            /** @enum {string} */
            role: "system" | "user" | "assistant" | "tool";
            content: string;
            name?: string;
        };
        ChatCompletionsResponse: {
            id?: string;
            object?: string;
            /** Format: int64 */
            created?: number;
            model?: string;
            choices?: {
                index?: number;
                finish_reason?: string;
                message?: components["schemas"]["ChatMessage"];
            }[];
            usage?: components["schemas"]["TokenUsage"];
        };
        TokenUsage: {
            prompt_tokens?: number;
            completion_tokens?: number;
            total_tokens?: number;
        };
        LegacyCompletionsRequest: {
            model: string;
            prompt: string;
            max_tokens?: number;
            temperature?: number;
            stream?: boolean;
        };
        LegacyCompletionsResponse: {
            id?: string;
            object?: string;
            created?: number;
            choices?: {
                text?: string;
                index?: number;
                finish_reason?: string;
            }[];
            usage?: components["schemas"]["TokenUsage"];
        };
        ResponsesRequest: {
            model?: string;
            input?: {
                [key: string]: unknown;
            }[];
        };
        ResponsesResponse: {
            id?: string;
            status?: string;
            output?: {
                [key: string]: unknown;
            }[];
        };
        ImagesGenerationRequest: {
            model: string;
            prompt: string;
            size?: string;
        };
        ImagesGenerationResponse: {
            created?: number;
            data?: {
                url?: string;
            }[];
        };
        GeminiGenerateRequest: {
            contents?: components["schemas"]["GeminiContent"][];
            safetySettings?: {
                [key: string]: unknown;
            }[];
        };
        GeminiContent: {
            role?: string;
            parts?: {
                [key: string]: unknown;
            }[];
        };
        GeminiGenerateResponse: {
            candidates?: {
                content?: components["schemas"]["GeminiContent"];
                finishReason?: string;
            }[];
            usageMetadata?: {
                [key: string]: unknown;
            };
        };
        GeminiCountTokensRequest: {
            contents?: components["schemas"]["GeminiContent"][];
        };
        GeminiCountTokensResponse: {
            totalTokens?: number;
        };
        GeminiModelsResponse: {
            models?: components["schemas"]["GeminiModel"][];
        };
        GeminiModelResponse: {
            model?: components["schemas"]["GeminiModel"];
        };
        GeminiModel: {
            name?: string;
            displayName?: string;
            description?: string;
        };
        VariantConfig: {
            fake_streaming_prefix?: string;
            anti_truncation_prefix?: string;
            thinking_suffixes?: string[];
            search_suffix?: string;
            custom_prefixes?: string[];
            custom_suffixes?: string[];
        };
        AssemblyDashboard: {
            overview?: {
                [key: string]: unknown;
            };
            models?: {
                [key: string]: unknown;
            };
            credentials?: {
                [key: string]: unknown;
            };
        };
        AssemblyPlanDiff: {
            openai?: components["schemas"]["PlanDiffEntry"];
            gemini?: components["schemas"]["PlanDiffEntry"];
            variant_changed?: boolean;
        };
        PlanDiffEntry: {
            add?: string[];
            remove?: string[];
        };
        RoutingState: {
            sticky?: number;
            cooldowns?: components["schemas"]["RoutingCooldown"][];
        };
        RoutingCooldown: {
            credential_id?: string;
            strikes?: number;
            remaining_sec?: number;
            /** Format: date-time */
            until?: string;
        };
        ErrorResponse: {
            error: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description 请求无效或参数错误 */
        Error400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 未授权 */
        Error401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 资源未找到 */
        Error404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listOpenAIModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenAIModelsResponse"];
                };
            };
            400: components["responses"]["Error400"];
        };
    };
    getOpenAIModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 模型 ID。 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenAIModelResponse"];
                };
            };
            400: components["responses"]["Error400"];
            /** @description 未找到 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createChatCompletion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCompletionsRequest"];
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatCompletionsResponse"];
                };
            };
            400: components["responses"]["Error400"];
            401: components["responses"]["Error401"];
        };
    };
    createLegacyCompletion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LegacyCompletionsRequest"];
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegacyCompletionsResponse"];
                };
            };
            400: components["responses"]["Error400"];
        };
    };
    createResponses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResponsesRequest"];
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsesResponse"];
                };
            };
            400: components["responses"]["Error400"];
        };
    };
    generateImages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImagesGenerationRequest"];
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImagesGenerationResponse"];
                };
            };
            400: components["responses"]["Error400"];
        };
    };
    generateGeminiContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeminiGenerateRequest"];
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeminiGenerateResponse"];
                };
            };
            400: components["responses"]["Error400"];
        };
    };
    streamGeminiContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeminiGenerateRequest"];
            };
        };
        responses: {
            /** @description 事件流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["Error400"];
        };
    };
    countGeminiTokens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeminiCountTokensRequest"];
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeminiCountTokensResponse"];
                };
            };
            400: components["responses"]["Error400"];
        };
    };
    listGeminiBetaModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeminiModelsResponse"];
                };
            };
            400: components["responses"]["Error400"];
        };
    };
    getGeminiBetaModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeminiModelResponse"];
                };
            };
            400: components["responses"]["Error400"];
            404: components["responses"]["Error404"];
        };
    };
    uploadCredential: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    filename?: string;
                    credentials: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description 上传成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                        filename?: string;
                    };
                };
            };
            400: components["responses"]["Error400"];
        };
    };
    validateCredential: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description 校验结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        valid?: boolean;
                        problems?: string[];
                    };
                };
            };
            400: components["responses"]["Error400"];
        };
    };
    validateCredentialBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description 批次校验结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            400: components["responses"]["Error400"];
        };
    };
    getVariantConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        config?: components["schemas"]["VariantConfig"];
                    };
                };
            };
            400: components["responses"]["Error400"];
        };
    };
    updateVariantConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantConfig"];
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error400"];
        };
    };
    generateVariants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        variants?: string[];
                    };
                };
            };
            400: components["responses"]["Error400"];
        };
    };
    parseModelFeatures: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    models?: string[];
                };
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error400"];
        };
    };
    getAssemblyDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssemblyDashboard"];
                };
            };
            400: components["responses"]["Error400"];
        };
    };
    getRoutingState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutingState"];
                };
            };
            400: components["responses"]["Error400"];
        };
    };
    dryRunAssemblyPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    plan: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        diff?: components["schemas"]["AssemblyPlanDiff"];
                        plan?: Record<string, never>;
                    };
                };
            };
            400: components["responses"]["Error400"];
        };
    };
    listAssemblyPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        plans?: Record<string, never>[];
                    };
                };
            };
            400: components["responses"]["Error400"];
        };
    };
    createAssemblyPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    include?: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error400"];
        };
    };
    getAssemblyPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error400"];
            404: components["responses"]["Error404"];
        };
    };
    deleteAssemblyPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error400"];
            404: components["responses"]["Error404"];
        };
    };
    applyAssemblyPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error400"];
            404: components["responses"]["Error404"];
        };
    };
    rollbackAssemblyPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error400"];
            404: components["responses"]["Error404"];
        };
    };
    diffApplyAssemblyPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error400"];
            404: components["responses"]["Error404"];
        };
    };
    diffRollbackAssemblyPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error400"];
            404: components["responses"]["Error404"];
        };
    };
    persistRoutingState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error400"];
        };
    };
    restoreRoutingState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error400"];
        };
    };
    clearRoutingCooldowns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    all?: boolean;
                    credentials?: string[];
                };
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        cleared?: string[];
                        skipped?: string[];
                        total_before?: number;
                        total_after?: number;
                    };
                };
            };
            400: components["responses"]["Error400"];
        };
    };
}
